name: Convert README to PDF

on:
  push:
    paths:
      - README.md
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert README.md to PDF
      run: pandoc README.md -o README.pdf

    - name: Commit and push the PDF
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add README.pdf
        git commit -m "Automated PDF conversion of README.md"
        git push origin HEAD:main
